# -*- coding: utf-8 -*-
#
# Knowage documentation build configuration file
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# General information about the project.
project = u'Knowage'
copyright = u'2014-2024, Knowage Labs'
author = u'Knowage Labs'

extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.imgmath',
    'sphinx.ext.ifconfig',
    'sphinx.ext.duration',
    'sphinx.ext.doctest',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
]

exclude_patterns = ['_build','functionalities-guide/Manuals/*.rst','functionalities-guide/Manuals/imageThumbinals/*.rst']

html_theme = 'sphinx_rtd_theme'
